In [3]:
import numpy as np

In [12]:
# 1-D NUMPY ARRAY
a1 = np.array([1,2,3,4])
a1.ndim

1

In [11]:
a2 = np.array([[1,2,3],[4,5,6]])
a2.ndim

2

In [13]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3.ndim

3

In [16]:
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
b = np.zeros((4,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
c = np.arange(24).reshape(4,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [35]:
c[1:,1:3]

array([[ 7,  8],
       [13, 14],
       [19, 20]])

In [33]:
c[2,2:]

array([14, 15, 16, 17])

In [20]:
c[2,2]

14

In [21]:
c[3,5]

23

In [24]:
# SLICING
c[0,:]

array([0, 1, 2, 3, 4, 5])

In [25]:
c[:,2]

array([ 2,  8, 14, 20])

In [31]:
c[1,3:]

array([ 9, 10, 11])

**STACKING**

In [51]:
d = np.arange(20).reshape(5,4)
e = np.random.random(20).reshape(5,4)
f = np.hsplit(d,2)
d
# f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
f

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

**SORT**

In [58]:
g = np.array([4,2,8,1])
g
np.sort(g)

array([1, 2, 4, 8])

In [63]:
h = np.array([[1,6,9],[4,5,3]])
h

array([[1, 6, 9],
       [4, 5, 3]])

In [64]:
np.sort(h,axis = 0)

array([[1, 5, 3],
       [4, 6, 9]])

In [75]:
np.append(g,30)

array([  4, 300,  30])

In [82]:
e = np.array([3,4,5,6])
e

array([3, 4, 5, 6])

In [83]:
f = np.array([7,8,9,10])
f

array([ 7,  8,  9, 10])

In [87]:
i = np.concatenate((e,f),axis=0)
i

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.unique
np.expand_dims
np.where
np.argmax
np.argmin
np.cumsum
np.comprod
np.percentile
np.historgam
np.corrcoef
np.isin
np.flip
np.put
np.delete
np.union1d(,)
np.intersection1d(,)
np.setdiff1d(,)
np.setxor1d(,)
np.in1d(,)
np.clip( , max =__, min=___)