In [ ]:
import numpy as np

In [ ]:
# ADVANCE INDEXING


In [ ]:
a1= np.array([1,2,3,4,5,6,7,8,9,10])  #1D ARRAY
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a2 = np.arange(12).reshape(4,3)   #2D ARRAY
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a3 = np.array([[[1,2,3,4],[6,7,8,9]],[[10,11,12,13],[14,15,16,17]]])     #3D ARRAY
a3

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

In [ ]:
a2[[0,2,3]]  #all the rows what ever your row it is just pass the index of the row
a2[:,[0,1]]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [ ]:
# RANDOMLY GENERATED ARRAY

In [ ]:
c1 = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
c1>20

array([[ True, False,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [ ]:
c1[c1>20]

array([48, 49, 58, 50, 43, 93, 74, 69, 86, 93, 58, 24, 22, 52, 88, 97, 39,
       48, 87])

In [ ]:
c1[c1<20]

array([ 1,  2,  6,  2, 15])

In [ ]:
c1[c1%4==0]

array([48, 24, 52, 88, 48])

In [ ]:
c1[~(c1%4==0)]

array([ 1, 49,  2,  6,  2, 58, 50, 43, 93, 74, 69, 86, 93, 58, 22, 97, 39,
       87, 15])

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.ndim

3

In [ ]:
# FANCY INDEXING

In [ ]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
a3[0:1]

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [21]:
a2 = np.arange(12).reshape(4,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
a2[[0,1,3]]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11]])

In [25]:
a2[:,[1]]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [33]:
a3 = np.arange(24).reshape(2,4,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [39]:
b3 = np.arange(12,24).reshape(2,2,3)
b3

array([[[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [41]:
b3[1,:,[1]]

array([[19, 22]])

In [42]:
b3[1,:,[2]]

array([[20, 23]])

In [43]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [45]:
a3[0,:,[1]]

array([[ 1,  4,  7, 10]])

In [46]:
a3[0,[0]]

array([[0, 1, 2]])

In [47]:
a3[a3>20]

array([21, 22, 23])

In [48]:
a2[a2<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a2[~(a2>10)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:



                                                            #  RANDOMLLY GENERATED ARRAY





In [50]:
c1 = np.random.randint(1,25,12).reshape(4,3)

In [51]:
c1

array([[24,  2, 13],
       [16,  9, 12],
       [ 1, 10,  9],
       [24,  9, 21]])

In [ ]:



                                                         # WORKING THE MISSING DATA VALUE





In [53]:
a = np.array([1,2,3,4,5,6,np.nan,7,8,9,np.nan,10])
a

array([ 1.,  2.,  3.,  4.,  5.,  6., nan,  7.,  8.,  9., nan, 10.])

In [ ]:
# how to hendling missing data

In [54]:
np.isnan(a)

array([False, False, False, False, False, False,  True, False, False,
       False,  True, False])