In [ ]:
import numpy as np

**Create the empty Numpy Array**

In [ ]:
a1 = np.empty((3,4))
a1

array([[2.5e-323, 2.5e-323, 2.5e-323, 2.5e-323],
       [2.5e-323, 2.5e-323, 2.5e-323, 2.5e-323],
       [2.5e-323, 2.5e-323, 2.5e-323, 2.5e-323]])

**Create the Full Numpy Array**

In [ ]:
# In NumPy, "full" refers to an array where all elements are initialized with a specific value.

a2 = np.full((3,4),5)
a2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Create the Numpy Array filled with all zeros**

In [ ]:
# 1D
arra1 = np.zeros(5)
arra1

array([0., 0., 0., 0., 0.])

In [ ]:
# 3D
arra3 = np.zeros((3,3,3))
arra3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

**Create the Numpy array filled with all ones**

In [ ]:
arr1 = np.ones(6)
arr2 = np.ones((3,4))
arr3 = np.ones((2,4,5))
print("1d array with ones",arr1)
print("2d array with ones",arr2)
print("3d array with ones",arr3)

1d array with ones [1. 1. 1. 1. 1. 1.]
2d array with ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3d array with ones [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


**Check whether the numpy array contain a specific row**

In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]
                ])
print(arr)

print([1,2,3,4,5] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True


**How to Remove rows in Numpy array that contains non-numeric values?**

In [2]:
import numpy as np

n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing NaN values:")
clear_arr = n_arr[~np.isnan(n_arr).any(axis = 1)]
print(clear_arr)

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing NaN values:
[[10.5 22.5  3.8]]


**Remove single dimnesional entries from the shape of an array**

In [7]:
import numpy as np

my_arr = np.array([[[1,2,3],[5,6,7]]])
print(my_arr)
print(my_arr.shape)

# tp remove the 1 we use  . squeeze() function

new_arr = np.squeeze(my_arr)
print(new_arr)
print(new_arr.shape)

[[[1 2 3]
  [5 6 7]]]
(1, 2, 3)
[[1 2 3]
 [5 6 7]]
(2, 3)


**Find the number of occurrences of a sequence in a NumPy array**

In [10]:
# importing package
import numpy

# create numpy array
arr = numpy.array([[2, 8, 9, 4],
				[9, 4, 9, 4],
				[4, 5, 9, 7],
				[2, 9, 4, 3]])

# Counting sequence
output = repr(arr).count("9, 4")

# view output
print(output)


4


**Find the most frequent value in a NumPy array**

In [19]:
import numpy as np

arr = np.array([1,2,3,4,6,4,1,3,7,4])

counts = np.bincount(arr)
print(counts)

[0 2 1 2 3 0 1 1]


In [ ]:
# Explanation of the code and the output explain by the this image which is present in the below

Screenshot 2025-02-11 122604.png

**Combining not join a one and a two-dimensional NumPy Array**

**Combine and join are two thing**

**COMBINE**

In [31]:
# Combining

import numpy as np

num_1 = np.arange(5)
print(" One dimensional array:",num_1)

num_2 = np.arange(10).reshape(2,5)
print("One dimensional array",num_2)

for a,b in np.nditer([num_1,num_2]):
        print("%d:%d" % (a,b),)

 One dimensional array: [0 1 2 3 4]
One dimensional array [[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


**JOIN**

In [39]:
# VSTACK

In [37]:
print("First array",num_1)

print("Second array",num_2)

cum = np.vstack([num_1,num_2])
print("The combined result",cum)

First array [0 1 2 3 4]
Second array [[0 1 2 3 4]
 [5 6 7 8 9]]
The combined result [[0 1 2 3 4]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
# HSTACK

In [ ]:
print("First array",num_1)

print("Second array",num_2)

cum = np.hstack([num_1,num_2])
print("The combined result",cum)

In [40]:
# CONCATENATE
# but all the input array must be of same size

In [42]:
num_1d = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [7,8,9,10]])
print("First array",num_1d)

num_2d = np.array([[3,4,2,1],
                   [6,5,4,3],
                   [9,1,10,3]])
print("Second array",num_2d)

cum = np.concatenate([num_1d,num_2d],axis = 0)
print("The combined result",cum)

First array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]
Second array [[ 3  4  2  1]
 [ 6  5  4  3]
 [ 9  1 10  3]]
The combined result [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 3  4  2  1]
 [ 6  5  4  3]
 [ 9  1 10  3]]
