In [4]:
import numpy as np

In [10]:
a1 = np.array([12,34,56,78,9,23,25,568,12])
print(a1)
a1.ndim

[ 12  34  56  78   9  23  25 568  12]


1

In [11]:
a2 = np.arange(12).reshape(4,3)
print(a2)
a2.ndim

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


2

In [12]:
a3 = np.array([[[1,2,3,4],[5,6,7,8]],[[8,9,2,5],[3,5,1,8]]])
print(a3)
a3.ndim

[[[1 2 3 4]
  [5 6 7 8]]

 [[8 9 2 5]
  [3 5 1 8]]]


3

In [15]:
np.argmax(a3,axis=0)

array([[1, 1, 0, 1],
       [0, 0, 0, 0]])

In [17]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.argmax(a2,axis=0)

array([3, 3, 3])

In [18]:
a1

array([ 12,  34,  56,  78,   9,  23,  25, 568,  12])

In [19]:
np.cumsum(a1)

array([ 12,  46, 102, 180, 189, 212, 237, 805, 817])

In [20]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
print(np.cumsum(a2,axis=0))
print(np.cumsum(a2,axis=1))

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]


In [26]:
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 9, 2, 5],
        [3, 5, 1, 8]]])

In [28]:
print(np.cumsum(a3,axis=0))
print(np.cumsum(a3,axis=1))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 11  5  9]
  [ 8 11  8 16]]]
[[[ 1  2  3  4]
  [ 6  8 10 12]]

 [[ 8  9  2  5]
  [11 14  3 13]]]


In [29]:
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 9, 2, 5],
        [3, 5, 1, 8]]])

In [30]:
np.percentile(a3,100)

np.float64(9.0)

In [31]:
a1 = np.arange(12,24)
a1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [33]:
np.histogram(a1,bins=[10,20,30,40,50,60])


(array([8, 4, 0, 0, 0]), array([10, 20, 30, 40, 50, 60]))

In [35]:
np.corrcoef(a3,a2)

ValueError: m has more than 2 dimensions

In [37]:
a1 = np.array([2,4,2,6,8,46,23,3,8,3,8,23,9,0,5])
a1

array([ 2,  4,  2,  6,  8, 46, 23,  3,  8,  3,  8, 23,  9,  0,  5])

In [39]:
iteam = [2,4,8,5]
np.isin(a1,iteam)

array([ True,  True,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True])

In [43]:
print(a1)
print(np.flip(a1))

[ 2  4  2  6  8 46 23  3  8  3  8 23  9  0  5]
[ 5  0  9 23  8  3  8  3 23 46  8  6  2  4  2]


In [44]:
print(a2)
print(np.flip(a2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[11 10  9]
 [ 8  7  6]
 [ 5  4  3]
 [ 2  1  0]]


In [42]:
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 9, 2, 5],
        [3, 5, 1, 8]]])

In [45]:
a1

array([ 2,  4,  2,  6,  8, 46, 23,  3,  8,  3,  8, 23,  9,  0,  5])

In [47]:
print(np.put(a1,[1,3],[64,66]))

None


In [48]:
a1

array([ 2, 64,  2, 66,  8, 46, 23,  3,  8,  3,  8, 23,  9,  0,  5])

In [50]:
np.clip(a1,a_min = 2,a_max = 66)

array([ 2, 64,  2, 66,  8, 46, 23,  3,  8,  3,  8, 23,  9,  2,  5])