In [1]:
import numpy as np

In [2]:
z1 = np.random.randint(1,100,15)
z1

array([34, 65, 75, 61,  8, 76, 20, 58, 83, 99, 23,  3, 29, 10, 54])

In [3]:
np.sort(z1)

array([ 3,  8, 10, 20, 23, 29, 34, 54, 58, 61, 65, 75, 76, 83, 99])

In [4]:
z2 = np.random.randint(1,100,24).reshape(6,4)
z2

array([[67, 36, 54, 53],
       [25, 62, 73, 25],
       [22, 78, 89, 42],
       [57, 77, 14, 59],
       [24, 68, 32,  2],
       [52, 15, 51, 33]])

In [5]:
np.sort(z2)

array([[36, 53, 54, 67],
       [25, 25, 62, 73],
       [22, 42, 78, 89],
       [14, 57, 59, 77],
       [ 2, 24, 32, 68],
       [15, 33, 51, 52]])

In [ ]:
# row wise sorting

In [6]:
np.sort(z2,axis=1)

array([[36, 53, 54, 67],
       [25, 25, 62, 73],
       [22, 42, 78, 89],
       [14, 57, 59, 77],
       [ 2, 24, 32, 68],
       [15, 33, 51, 52]])

In [7]:
# COLUMB WISE SORTING

In [8]:
np.sort(z2,axis=0)

array([[22, 15, 14,  2],
       [24, 36, 32, 25],
       [25, 62, 51, 33],
       [52, 68, 54, 42],
       [57, 77, 73, 53],
       [67, 78, 89, 59]])

In [ ]:



                                                              # APPEND FUNCTION IN NUMPY




In [9]:
z1

array([34, 65, 75, 61,  8, 76, 20, 58, 83, 99, 23,  3, 29, 10, 54])

In [12]:
np.append(z1,200)              #Append in 1d array

array([ 34,  65,  75,  61,   8,  76,  20,  58,  83,  99,  23,   3,  29,
        10,  54, 200])

In [14]:
z2

array([[67, 36, 54, 53],
       [25, 62, 73, 25],
       [22, 78, 89, 42],
       [57, 77, 14, 59],
       [24, 68, 32,  2],
       [52, 15, 51, 33]])

In [15]:
                               #Append in 2d array

In [20]:
np.append(z2,np.ones((z2.shape[0],1)),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [19]:
np.ones((z2.shape[0], 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [21]:


                                #  CONCATIATE FUNCTION IN NUMPY ARRAY




In [28]:
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(2,3)

print(a1)
print(a2)


np.concatenate((a1,a2),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])