In [ ]:
# numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([3,4,5,6])

In [ ]:
np.array([3,4,5],dtype='complex')

array([3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
c = np.arange(1,11)

In [ ]:
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
d = np.array([7,8,9],dtype='float')
d

array([7., 8., 9.])

In [ ]:
f = np.arange(12,16)

In [ ]:
f


array([12, 13, 14, 15])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.8432973 , 0.18387879, 0.04544518, 0.09593024],
       [0.20855524, 0.53093866, 0.96608912, 0.58407164],
       [0.60950904, 0.13062693, 0.39884244, 0.77686444]])

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(34)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
# array attribute

In [ ]:
a1 = np.array(10)

In [ ]:
a1

array(10)

In [ ]:
a1.ndim

0

In [ ]:
a2 = np.array([1,2,3,4,5])

In [ ]:
a2.shape
# a2.ndim

(5,)

In [ ]:
a3 = np.array(([1,2,3,4],[5,6,7,8]))
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a3.ndim

2

In [ ]:
a3.shape

(2, 4)

In [ ]:
a3.size

8

In [ ]:
a3.itemsize

8

In [ ]:
a3.dtype


dtype('int64')

In [ ]:
b1 = np.array([1,2,3,4])

In [ ]:
b1.ndim

1

In [ ]:
b1.shape

(4,)

In [ ]:
b1.size

4

In [ ]:
b1.itemsize

8

In [ ]:
b1.dtype

dtype('int64')

In [ ]:
c1 = np.array(([1,2,3,4],[5,6,7,8]))
c1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
c1.ndim

2

In [ ]:
c1.size

8

In [ ]:
c1.shape

(2, 4)

In [ ]:
c1.dtype

dtype('int64')

In [ ]:
c3 = np.array(([1,2,3],[4,5,6],[7,8,9]))
c3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c3.shape

(3, 3)

In [ ]:
c3.size

9

In [ ]:
c3.dtype

dtype('int64')

In [ ]:
c3.itemsize

8

In [ ]:
c3.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
# scaler operation

In [ ]:
a*23

()

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4]) #1 d array
a2 = np.array(([1,2,3,4],[5,6,7,8]))  #2d array
a3 = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12])) #3d array

In [ ]:
a1
a1.shape
a1.size
a1.itemsize
a1.dtype
a1.ndim

4

In [ ]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a1.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# ARRAY OPERATIONS

In [ ]:
# scaler

In [ ]:
a2*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [ ]:
# relation operation

In [ ]:
a1>15

array([False, False, False, False])

In [ ]:
# vector operation

In [ ]:
a1+a2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [ ]:
a3+a1

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [ ]:
np.max(a1)

np.int64(4)

In [ ]:
np.max(a2)

np.int64(8)

In [ ]:
np.max(a3)

np.int64(12)

In [ ]:
np.min(a2)

np.int64(1)

In [ ]:
np.sum(a3)

np.int64(78)

In [ ]:
np.prod(a2)

np.int64(40320)

In [ ]:
a3


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.max(a3,axis=0)

array([ 9, 10, 11, 12])

In [ ]:
np.argmax(a3)

np.int64(11)

In [ ]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.argmax(a2)

np.int64(7)

In [ ]:
np.sum(a3)

np.int64(78)

In [ ]:
a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.sum(a3,axis=0)

array([15, 18, 21, 24])

In [ ]:
np.sum(a3,axis=1)

array([10, 26, 42])

In [ ]:
np.sin(a2)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(4,3)

In [ ]:
np.dot(a2,a1)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [ ]:
d1 = np.arange(10,21)

In [ ]:
d1.reshape(1,-1)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
d2 = np.arange(1,65)

In [ ]:
d2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
d2.reshape(8,8)
d2.rashape()

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [ ]:
d3 = np.arange(1,73)
d3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72])

In [ ]:
d3.reshape(3,3,8)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69, 70, 71, 72]]])

In [ ]:
np.log(a2)

/tmp/ipython-input-84-970536687.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
# ROUND

In [ ]:
np.round(3.4)

np.float64(3.0)

In [ ]:
f1 = 3.2
np.round(f1)

np.float64(3.0)

In [1]:
# numpy array

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4])   #1d arrray

In [129]:
a2 = np.array(([1,2,3,4],[5,6,7,8])) #2d array

In [33]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])       #3D NUMPY ARRAY
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
a4 = np.arange(1,15)

In [10]:
a4


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.random.random((4,5))

array([[0.10686822, 0.31197778, 0.10906769, 0.95576907, 0.87582366],
       [0.1780607 , 0.40900712, 0.88707906, 0.00356276, 0.27516478],
       [0.83425594, 0.1618964 , 0.30950835, 0.97486056, 0.53930832],
       [0.33092992, 0.1390394 , 0.68629675, 0.69153961, 0.71329462]])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
a1.ndim
a1.shape
a1.size
a1.itemsize
a1.dtype


dtype('int64')

In [26]:
a2.ndim

2

In [34]:
a3.ndim

3

In [40]:
a3.astype(np.int32)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [42]:
a2 > 13

array([[False, False, False, False],
       [False, False, False, False]])

In [43]:
a1+a2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [45]:
np.max(a1)

np.int64(4)

In [50]:
a2
# np.max(a2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
np.max(a2)
np.min(a2)
np.sum(a2)
np.sum(a2,axis=0)
np.min(a2,axis=1)
np.min(a2,axis=0)
np.max(a2,axis=0)
np.max(a2,axis=1)

array([4, 8])

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
np.prod(a3)
np.sum(a3)
np.min(a3,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# ROUND

In [73]:
np.round(np.random.random((2,3)))

array([[0., 0., 1.],
       [1., 1., 1.]])

In [79]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
a2[0,1]

np.int64(2)

In [85]:
a2[0,2]
a2[1,1]
a2[1,2]

np.int64(7)

In [86]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
a3[0,0,1]
a3[0,1,1]
a3[0,1,2]

np.int64(6)

In [90]:
a3[1,0,2]

np.int64(9)

In [91]:
a1

array([1, 2, 3, 4])

In [95]:
a1[1:3]

array([2, 3])

In [96]:
a1 = np.array([1,2,3,4,5,6,7,8,9,2,5,1,8,3,23,7,2,1,2,8,32,23,8,23])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  5,  1,  8,  3, 23,  7,  2,
        1,  2,  8, 32, 23,  8, 23])

In [105]:
a1[1:11]
a1[0:11]
a1[5:16]
a1[:26]
a1[11:]

array([ 1,  8,  3, 23,  7,  2,  1,  2,  8, 32, 23,  8, 23])

In [131]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
a2[1,1:2]

array([6])

In [114]:
b1=np.arange(1,13)
b1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
b2 =np.arange(12,24)
b2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [120]:
b1+b2

array([13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35])

In [121]:
b3 = b2+b1

In [122]:
b3

array([13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35])

In [123]:
b3.reshape(4,3)

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [139]:
b3[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [134]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
a2[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
a2[0,2]

np.int64(3)

In [141]:
a2[1,3]

np.int64(8)

In [145]:
a2[1,:]
a2[0,:] #phli row ke sare columb
a2[:,0] #phle colmb ke sare rows

array([1, 5])